name: CI - Streamlit DuckDB

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configurar Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Verificar sintaxe com flake8
      run: |
        pip install flake8
        flake8 .

    - name: Rodar testes
      run: |
        # Aqui você pode rodar seus testes, por exemplo:
        # pytest
        echo "Sem testes configurados - adapte aqui"

    - name: Testar execução do Streamlit (opcional)
      run: |
        python -m streamlit --version
